local _, ns = ...

-- The look Forever Unit Frames ships with, on top of the plain defaults in
-- Core/Settings.lua: preset[scope][key] = value. Only values that differ
-- from the plain defaults are listed. Saved profiles store differences
-- from these, so changing a value here changes it for everyone who kept
-- the default.
local PRESET = {
    general = {
        barTexture = "Blizzard Raid Bar",
        borderStyle = "GOLD",
        classIconY = 0,
        fontOutline = "OUTLINE",
        fontShadow = true,
        shadowAlpha = 13,
        shadowEnabled = true,
    },
    player = {
        buffsAnchor = "FRAME",
        buffsEnabled = true,
        buffsHighlightOwn = true,
        buffsMax = 24,
        buffsPerRow = 11,
        buffsSize = 18,
        buffsSpacing = 4,
        buffsY = 3,
        castbarAlwaysShow = true,
        castbarEnabled = true,
        debuffsAnchor = "CASTBAR",
        debuffsFramePoint = "BOTTOMLEFT",
        debuffsPoint = "TOPLEFT",
        debuffsX = -15,
        debuffsY = -4,
        healthColorMode = "CLASS",
        healthPercent = 74,
        height = 70,
        portraitMode = "LEFT",
        portraitStyle = "3D",
        textPowerLeft = "CURRENT_MAX",
        textPowerRight = "PERCENT",
        width = 300,
        x = -400,
    },
    target = {
        buffsAnchor = "FRAME",
        buffsHighlightOwn = true,
        buffsMax = 24,
        buffsPerRow = 5,
        buffsSize = 18,
        buffsSpacing = 4,
        castbarAlwaysShow = true,
        castbarX = 366,
        debuffsAnchor = "CASTBAR",
        debuffsFramePoint = "BOTTOMLEFT",
        debuffsMax = 24,
        debuffsPerRow = 12,
        debuffsPoint = "TOPLEFT",
        debuffsRowGrowth = "DOWN",
        debuffsSpacing = 4,
        debuffsX = -15,
        debuffsY = -4,
        healthColorMode = "CLASS",
        healthPercent = 74,
        height = 70,
        portraitMode = "LEFT",
        portraitStyle = "3D",
        textPowerLeft = "CURRENT_MAX",
        textPowerRight = "PERCENT",
        width = 300,
        x = 400,
    },
    targettarget = {
        buffsMax = 9,
        buffsSize = 14,
        healthColorMode = "CLASS",
        x = 640,
        y = -256,
    },
    focus = {
        powerPercent = 21,
        x = 575,
        y = 124,
    },
    party = {
        buffsAnchor = "FRAME",
        buffsFramePoint = "RIGHT",
        buffsMax = 8,
        buffsSpacing = 8,
        debuffsDispellable = true,
        healthColorMode = "CLASS",
        height = 65,
        showSurname = false,
        textHealthLeft = "CURRENT_MAX",
        textPowerLeft = "CURRENT_MAX",
        textPowerRight = "PERCENT",
        width = 195,
    },
}

ns.Settings.ApplyPreset(PRESET)
