-- Writes the settings reference of the GitHub wiki (docs/wiki/Settings-*.md
-- and _Sidebar.md) from the same sources the options window reads: the
-- menu (Options/Schema.lua), the English labels and hints, and the
-- defaults of the addon as shipped (preset included). Home.md and FAQ.md
-- are written by hand.
--
-- Run from the repository root:  tools/make_wiki
-- (loads the addon the way the tests do: tests/mock.lua, no game needed).
-- The output is deterministic; running it again changes nothing unless the
-- options did.

local H = _G.H
local ns = H.LoadShipped()
local S, L, Schema = ns.Settings, ns.L, ns.Schema

-- WIKI_OUT (optional): another folder, e.g. for the test that checks the
-- committed pages are current.
local OUT = (rawget(_G, "WIKI_OUT") or (ADDONDIR .. "/docs/wiki")) .. "/"
local FRAMES = { "player", "target", "targettarget", "focus", "pet", "party" }

local function label(key, fallback)
    local v = L[key]
    if v == nil or v == key then return fallback end
    return v
end

local function frameName(scope) return label("FRAME_" .. scope, scope) end

-- A value as the options window shows it.
local function valueText(def, v)
    if v == nil or v == "" then return "(none)" end
    local t = def.type
    if t == "bool" then return v and "On" or "Off" end
    if t == "enum" then return Schema.EnumText(def, v) or tostring(v) end
    if t == "color" then
        local hex = ("#%02x%02x%02x"):format(math.floor(v[1] * 255 + 0.5), math.floor(v[2] * 255 + 0.5),
            math.floor(v[3] * 255 + 0.5))
        local a = v[4] or 1
        if a < 1 then return ("`%s`, %d %% opaque"):format(hex, math.floor(a * 100 + 0.5)) end
        return "`" .. hex .. "`"
    end
    if t == "int" and v == 0 and def.zeroText then return label(def.zeroText, "0") end
    if t == "media" then return tostring(v) end
    return tostring(v)
end

-- What can be chosen: a range, or the enum's choices.
local function choices(def)
    local t = def.type
    if t == "int" then
        local range = ("%d – %d"):format(def.min or 0, def.max or 0)
        if def.zeroText then range = range .. (" (0: %s)"):format(label(def.zeroText, "0")) end
        return range
    end
    if t == "enum" and def.values == S.POINTS then
        return "Any of the 9 points (corners, edges, center)"
    end
    if t == "enum" then
        local list = {}
        for _, v in ipairs(def.values) do list[#list + 1] = Schema.EnumText(def, v) or v end
        return table.concat(list, ", ")
    end
    if t == "color" then return "Color" end
    if t == "media" then return def.mediaKind == "font" and "Font" or "Texture" end
    if t == "text" then return "Text (a spell name or ID)" end
    if t == "bool" then return "On, Off" end
    return ""
end

-- The frames an option is on (in the order of the navigation).
local function framesOf(def)
    local list = {}
    for _, scope in ipairs(FRAMES) do
        if S.AppliesTo(def, scope) then list[#list + 1] = scope end
    end
    return list
end

-- The default, per frame when it differs.
local function defaultText(def, scopes)
    if #scopes == 0 then return valueText(def, S.Default(def, "general")) end
    local groups, order = {}, {}
    for _, scope in ipairs(scopes) do
        local text = valueText(def, S.Default(def, scope))
        if not groups[text] then groups[text] = {}; order[#order + 1] = text end
        table.insert(groups[text], frameName(scope))
    end
    if #order == 1 then return order[1] end
    local parts = {}
    for _, text in ipairs(order) do parts[#parts + 1] = ("%s: %s"):format(table.concat(groups[text], ", "), text) end
    return table.concat(parts, "; ")
end

local function cell(s) return (tostring(s):gsub("|", "\\|"):gsub("\n", " ")) end

-- GitHub's anchor for a heading: lower case, spaces to hyphens, most
-- punctuation dropped.
local function anchor(title)
    return (title:lower():gsub("[^%w%s%-]", ""):gsub("%s", "-"))
end

-- What each frame tab is for (the page's first line).
local TAB_INTRO = {
    layout = "Size, position, the rows of the frame, portrait, markers, border, shadow and corners.",
    group = "The party only: how the members are arranged, their pets and their targets.",
    bars = "Colors and textures of the bars, shields, incoming heals, power colors and the druid's mana.",
    text = "What the texts on the title row and the bars show, how they read, and the font.",
    auras = "Buffs, debuffs, the party's dispellable debuffs and the player's totems.",
    status = "Icons and markers on the frame, combo points, threat, highlights and fading.",
    castbar = "Castbars, and the player's threat bar below them.",
}

local function write(name, lines)
    local fh = assert(io.open(OUT .. name, "w"))
    fh:write(table.concat(lines, "\n"), "\n")
    fh:close()
end

local GENERATED = "<!-- Generated by tools/make_wiki from the addon's own options. Do not edit by hand. -->"

-- One table per section: option, what it does, choices, default, frames.
local function section(lines, sec, keys, scopesFor, showFrames, level)
    lines[#lines + 1] = level .. " " .. label("SECTION_" .. sec.id, sec.id)
    lines[#lines + 1] = ""
    if sec.action then
        lines[#lines + 1] = ("Button: **%s**."):format(label("ACTION_" .. sec.action, sec.action))
        lines[#lines + 1] = ""
    end
    lines[#lines + 1] = showFrames and "| Option | What it does | Choices | Default | Frames |"
        or "| Option | What it does | Choices | Default |"
    lines[#lines + 1] = showFrames and "|---|---|---|---|---|" or "|---|---|---|---|"
    for _, key in ipairs(keys) do
        local def = S.Get(key)
        local scopes = scopesFor(def)
        local hint = label("HINT_" .. key, "")
        local row = { "**" .. cell(label("SETTING_" .. key, key)) .. "**", cell(hint), cell(choices(def)),
            cell(defaultText(def, scopes)) }
        if showFrames then
            local names = {}
            for _, scope in ipairs(scopes) do names[#names + 1] = frameName(scope) end
            row[#row + 1] = #scopes == #FRAMES and "all" or table.concat(names, ", ")
        end
        lines[#lines + 1] = "| " .. table.concat(row, " | ") .. " |"
    end
    lines[#lines + 1] = ""
end

-- General ---------------------------------------------------------------------------
local pages = {}
do
    local lines = { GENERATED, "", "# Settings: General", "",
        "The **General** page (top of the list on the left in `/fuf`) sets the look for every frame at once.",
        "Most of these can be overridden on a frame's own page; the frame then keeps its own value.",
        "The **Profile** tab (export, import, reset) is explained on the [[Home]] page.", "" }
    local body, toc = {}, { "**On this page:**", "" }
    for _, tab in ipairs(Schema.Tabs("general")) do
        if not tab.custom then
            local title = label("TAB_" .. tab.id, tab.id)
            body[#body + 1] = "## " .. title
            body[#body + 1] = ""
            local names = {}
            for _, sec in ipairs(tab.sections) do
                local keys = {}
                for _, key in ipairs(sec.keys) do
                    if S.AppliesTo(S.Get(key), "general") then keys[#keys + 1] = key end
                end
                if #keys > 0 then
                    section(body, sec, keys, function() return {} end, false, "###")
                    local name = label("SECTION_" .. sec.id, sec.id)
                    names[#names + 1] = ("[%s](#%s)"):format(name, anchor(name))
                end
            end
            toc[#toc + 1] = ("- **[%s](#%s):** %s"):format(title, anchor(title), table.concat(names, " · "))
        end
    end
    for _, l in ipairs(toc) do lines[#lines + 1] = l end
    lines[#lines + 1] = ""
    for _, l in ipairs(body) do lines[#lines + 1] = l end
    write("Settings-General.md", lines)
    pages[#pages + 1] = { "Settings-General", "General" }
end

-- Frame tabs: one page per tab, every frame that has the option listed.
for _, tab in ipairs(Schema.FRAME) do
    local title = label("TAB_" .. tab.id, tab.id)
    local lines = { GENERATED, "", "# Settings: " .. title, "",
        TAB_INTRO[tab.id] or "",
        "",
        ("The **%s** tab on each frame's page in `/fuf`. The last column says which frames have the option;"
            .. " a default that differs per frame is listed per frame."):format(title), "" }
    local body, names = {}, {}
    local any = false
    for _, sec in ipairs(tab.sections) do
        local keys = {}
        for _, key in ipairs(sec.keys) do
            if #framesOf(S.Get(key)) > 0 then keys[#keys + 1] = key end
        end
        if #keys > 0 then
            any = true
            section(body, sec, keys, framesOf, true, "##")
            local name = label("SECTION_" .. sec.id, sec.id)
            names[#names + 1] = ("[%s](#%s)"):format(name, anchor(name))
        end
    end
    lines[#lines + 1] = "**On this page:** " .. table.concat(names, " · ")
    lines[#lines + 1] = ""
    for _, l in ipairs(body) do lines[#lines + 1] = l end
    if any then
        local name = "Settings-" .. title:gsub("%s+", "-")
        write(name .. ".md", lines)
        pages[#pages + 1] = { name, title }
    end
end

-- Sidebar ---------------------------------------------------------------------------
do
    local lines = { GENERATED, "", "**[[Home]]**", "", "**[[FAQ]]**", "", "**Settings**", "" }
    for _, page in ipairs(pages) do lines[#lines + 1] = ("- [[%s|%s]]"):format(page[2], page[1]) end
    write("_Sidebar.md", lines)
end

WIKI_PAGES = pages
if not rawget(_G, "WIKI_OUT") then
    print(("wrote %d settings pages and the sidebar to docs/wiki/"):format(#pages))
end
